version: '3'

volumes:
  db_data_piwik:
  file_data_piwik:

services:
      
  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    command: --log-facility=-
    cap_add: 
      - NET_ADMIN
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:piwik.docker
      - proxy:welcome.docker

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  web:
    # this is "routing" all web traffic and knows
    # all other services in the SDN by their 
    # docker-compose names which are used in app.conf
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=piwik.docker
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - piwikweb
      
  piwikdb:
    image: mysql
    volumes:
      - ./piwikdb-init.d:/docker-entrypoint-initdb.d
      - db_data_piwik:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd12
      - MYSQL_DATABASE=piwik

  piwikapp:
    image: piwik:2.16.0
    volumes:
      - file_data_piwik:/var/www/html
      - ./config.ini.php:/var/www/html/config/config.ini.php
    links:
      - piwikdb:db
    depends_on:
      - piwikdb

  piwikweb:
    image: nginx
    hostname: piwik
    domainname: docker
    container_name: piwikweb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - file_data_piwik:/var/www/html
    links:
      - piwikapp:app
    depends_on:
      - piwikapp

  matomo:
    image: piwik:3.0.4-apache
    hostname: welcome
    domainname: docker
    links:
      - piwikdb:db
    environment:
      - VIRTUAL_HOST=welcome.docker
      - VIRTUAL_PORT=80
    depends_on:
      - piwikdb

  matomo2:
    image: piwik:3.3.0-apache
    hostname: welcome
    domainname: docker
    links:
      - piwikdb:db
    environment:
      - VIRTUAL_HOST=welcome.docker
      - VIRTUAL_PORT=80
    depends_on:
      - piwikdb

  cli:
    image: mysql
    command: mysql -h piwikdb -u root -p
    links:
      - piwikdb



