version: '3'

services:
      
  proxy:
    # this receives outside http/https traffic and
    # routes it to services in the SDN, it also
    # sets up SSL and offer the only open ports to
    # the outside - 80 and 443, we configure it
    # with a dnddock alias to allow testing it easily from the
    # host machine running these docker services
    image: jwilder/nginx-proxy
    environment:
      - DNSDOCK_ALIAS=piwik.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  dnsdock:
    # for this to work, the host machine needs /etc/resolvconf configs
    # see instructions at https://github.com/mskyttner/dns-test-docker
    # the aacebedo image is an update of tonistiigi/dnsdock:amd64-1.13.1
    # which has Dockerfile and docs available at Docker Hub
    # (note the static ip on the docker bridge)
    image: aacebedo/dnsdock:v1.15.0-amd64
    ports:
     - 172.17.0.1:53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    # this is "routing" all web traffic and knows
    # all other services in the SDN by their 
    # docker-compose names which are used in app.conf
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=piwik.docker
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./app.conf:/etc/nginx/conf.d/app.conf
    depends_on: 
      - piwikweb
      
  piwikdb:
    image: mysql
    volumes:
      - ./piwikdb-init.d:/docker-entrypoint-initdb.d
      - db_data_piwik:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd12
      - MYSQL_DATABASE=piwik

  piwikapp:
    image: piwik:2.16.0
    volumes:
      - file_data_piwik:/var/www/html
      - ./config.ini.php:/var/www/html/config/config.ini.php
    links:
      - piwikdb:db

  piwikweb:
    image: nginx
    container_name: piwikweb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - file_data_piwik:/var/www/html
    links:
      - piwikapp:app

  piwikneo:
    image: piwik:3.0.4-apache
    hostname: welcome
    domainname: docker
    links:
      - piwikdb:db
    environment:
      - VIRTUAL_HOST=welcome.docker
      - VIRTUAL_PORT=80
      - DNSDOCK_ALIAS=welcome.docker

  cli:
    image: mysql
    command: mysql -h piwikdb -u root -p
    links:
      - piwikdb

volumes:
  db_data_piwik:
  file_data_piwik:



